# MONGODB
MONGO:
  URI: "mongodb://localhost:27017"
  DBNAME: "Holiday"

REDIS:
  HOSTNAME: "localhost"
  PORT: 6379
  AUTH: false
  PASSWORD: "pass"
  CHANNEL: "Holiday"

NETWORK:
  NAME: "example network"
  IP: "example.com"
  WEBSITE: "https://example.com"
  STORE: "https://store.example.com"
  DISCORD: "https://discord.example.com"
  TWITTER: "https://twitter.com/examplenetwork"
  TEAMSPEAK: "ts.example.com"

SERVER:
  NAME: "hub-1"
  NICENAME: "Hub 1"
  FALLBACKSERVERNAME: "Lobby" # The Bungee ServerName to send to in server shutdowns
  CHAT:
    ENABLED: true
    FORMAT: "<prefix><player><suffix>&f: <message>" # Placeholders: <prefix> <player> <suffix> <message>
  BANNEDJOIN: false

STAFFMODE:
  ENABLED: true
  TELEPORTBACK: true
  VANISHONENABLE: true
  UPDATEVISIBILITY: false




FILTERS:
  SENDTOSTAFF: true
  MESSAGE: "&d[Filtered] &5[<server>] <player>&e: <message>" # Placeholders: <server> <player> <message>
  LOW:
    ALLOWMESSAGE: true
    LIST:
      - "cunt"
      - "anal"
      - "beaner"
      - "nazi"
      - "paki"
  HIGH:
    ALLOWMESSAGE: false
    MUTE: false
    MUTEDURATION: "3h"
    MUTEREASON: "Automute (<word>)" # Placeholder: <word>
    LIST:
      - "nigger"
      - "coon"
      - "faggot"
      - "nigga"

NAMEMC:
  ENABLED: false
  MESSAGE: "&eThank you for liking our NameMC"
  RANK:
    ENABLED: false
    NAME: "VOTER"

LUNAR:
  ENABLED: false
  NAMETAGS: true