
MONGO:
  URI: "mongodb://localhost:27017"
  DBNAME: "Holiday"

REDIS:
  HOSTNAME: "localhost"
  PORT: 6379
  AUTH: false
  PASSWORD: "pass"
  CHANNEL: "Holiday"

NETWORK:
  NAME: "example network"
  IP: "example.com"
  WEBSITE: "https://example.com"
  STORE: "https://store.example.com"
  DISCORD: "https://discord.example.com"
  TWITTER: "https://twitter.com/examplenetwork"
  TEAMSPEAK: "ts.example.com"

SERVER:
  NAME: "hub-1"
  NICENAME: "Hub 1"
  FALLBACKSERVERNAME: "hub-1" # The Bungee ServerName to send to in server shutdowns
  CHAT:
    ENABLED: true
    FORMAT: "<prefix><player><suffix>&7: <message>" # Placeholders: <prefix> <player> <suffix> <message>
  BANNEDJOIN: false
  DONATORJOINFULL: true
  WHITELISTMESAGE: "&eThe server is currently &cWhitelisted&e. \n &eYou need <rank> &eor above to be able to log into the server." # Placeholder: <rank>
  STAFFCHATPREFIX: '@' # Use only one Symbol

STAFFMODE:
  ENABLED: true
  TELEPORTBACK: true # Should leaving staffmode teleports you back to your entering location?
  VANISHONENABLE: true
  UPDATEVISIBILITY: false # Should The visibility be updated when a staff vanishes?

COOLDOWNS: # In Seconds
  HELPOP: 150
  REPORT: 300

DISABLEDCOMMANDS: # Lowercase
  CORE: # Only put Holiday's commands here if you want to disable it, you need to put all the aliases to fully disable a command.
    - "none" # Set this to none if you don't want any command to be disabled
  OTHER: # Put any plugins' command it to disable it
    - "/bukkit:"
  OPBYPASS: false # Only works for Other plugins' commands, not Holiday's commands
  MESSAGE: "&cThis command is disabled."

FILTERS:
  SENDTOSTAFF: true
  MESSAGE: "&d[Filtered] &5[<server>] <player>&e: <message>" # Placeholders: <server> <player> <message>
  LOW:
    ALLOWMESSAGE: true
    LIST:
      - "cunt"
      - "anal"
      - "beaner"
      - "nazi"
      - "paki"
  HIGH:
    ALLOWMESSAGE: false
    MUTE: false
    MUTEDURATION: "3h"
    MUTEREASON: "Automute (<word>)" # Placeholder: <word>
    LIST:
      - "nigger"
      - "coon"
      - "faggot"
      - "nigga"

NAMEMC:
  ENABLED: false
  MESSAGE: "&eThank you for liking our NameMC"
  RANK:
    ENABLED: false
    NAME: "VOTER"

LUNAR:
  ENABLED: false
  NAMETAGS: true

DISGUISE:
  NAMES:
    - "Stompaay"
    - "nepheloid"
    - "TheKEKS"
    - "Lyrik"
    - "KleinEsmeree"
    - "HANDSOMEPLT445"
    - "Garfi3Id"
    - "latteishorse12"
    - "Glueckspilz1"
    - "wxszz"
    - "CabotBoy13"
    - "NeoPlayZ_"
    - "EICushWaffel"
    - "Ender_Leon"
    - "SHAWTYSPAT"
    - "baxikkAngel__"
    - "pokeopoly85"
    - "DiamondDamonen"
    - "KingOfFire1334"
    - "MaliessIlmig"
    - "xxClementxx2002"
  SKINS:
    - "Hiss_Y"
    - "ka_0221"
    - "_BrokenMouse_"
    - "zacles"
    - "badpoo"
    - "younbuffalo"
    - "Fruitberry"
    - "uchtiv"
    - "iil"
    - "tartzy"
    - "Dawnlend"
    - "zombeep"
    - "Nexo_Craft"
    - "M4xtern"
    - "mxyrey"
    - "tooty22"
    - "oT4q"
    - "VerifiedMoves"
    - "Ducksolz"
    - "7922"