name: "Holiday"
main: "me.andyreckt.holiday.bukkit.Holiday"
version: "${git.commit.id.abbrev}"
api-version: "1.8"
authors: ["AndyReckt"]
description: "Holiday is an Open Source server core which manages ranks, punishments, and more."
website: "https://github.com/AndyReckt/Holiday"
softdepend:
  - "Vault"
  - "PlaceholderAPI"
