name: "StaffAddon"
main: "me.andyreckt.holiday.staff.Staff"
version: "${git.commit.id.abbrev}"
api-version: "1.8"
authors: ["AndyReckt"]
description: "Holiday's Staff addon"
website: "https://github.com/AndyReckt/Holiday"
depend: ["Holiday"]
